### ISSUE TITLE
Issues with message state

### ISSUE THREAD

**Issue by bkraul** [zulip/zulip-flutter#1525]
Installed the Beta app 0.029 due to constant issues with messages not being delivered on the mobile one (legacy).

There seem to still be issues with message status, where the app says "Message isn't sent" but it actually does deliver the message, also there is the progress bar almost all the time at the top. Is there any logging information we could check from either the app or the server that could help with this?

Also, on the device affected by the issues described, the messages do not show up on the chat until tapping on the received push notification.

![Image](https://github.com/user-attachments/assets/9d742a0b-eccc-4e1e-8a94-be1d84283db3)

**Comment by gnprice** [comment]
Thanks for the report.

It sounds like the app is getting into a state where it's not receiving events from the server: that's what drives the progress indicator at the top, and it would mean that new messages don't arrive.

On the other hand when you navigate to a given conversation, the app makes a request to the server to fetch the messages for that conversation. So those requests are succeeding, which is why you do see the new messages when you do that.

It's possible this is an instance of an issue we've seen just a couple of times before, described at https://github.com/zulip/zulip-flutter/issues/514#issuecomment-2433558556.

(The symptom where the message you sent is marked with "message isn't sent", when in reality it was successfully sent, is a bug in v0.0.29 which has been fixed; the fix will be in the next beta release next week. Details at https://github.com/zulip/zulip-flutter/pull/1453#discussion_r2103695368 . The new version's behavior is that it would show a progress indicator on that message, given the broader issue that the app isn't getting events.)

**Comment by bkraul** [comment]
I have downloaded the new version, will be testing this today and report back.

**Comment by gnprice** [comment]
Thanks for the follow-up. (I've taken the liberty of editing the formatting around those screenshots so that it's easier to read the thread before and after them.)


> * An individual bar now shows up for every message, and the immediate behavior is that the messages are being shown out of order, but even though the bars remain, the messages are still delivered.
> * New messages at times do not show up unless the notification is tapped to see new messages.

These indicate the app is getting into a state where it's not receiving events from the server: that's what drives the progress indicator at the top, and it would mean that new messages don't arrive.

I'd be interested in digging into that further to try to get to the bottom of it. If you'd like to make a Zulip account [on chat.zulip.org](https://zulip.com/development-community/) and start a thread in the #mobile channel, that would be the best place to ask questions interactively and go into detail.

(I'll be OOO tomorrow through next week, but other members of the team might have questions to help debug in the meantime.)


> * Sometimes all messages disappear and and a circle animation shows on middle.

This is expected immediately after the app has re-established an event queue (effectively its connection to get data from the server). It's normally very quick, though — I'd have to be very quick on the trigger finger to manage to capture a screenshot of it. It sounds like for you it's sticking around much longer, which isn't expected.

This would also be something to dig into in a Zulip thread. It might be related to whatever's causing the other symptoms above for you.

**Comment by gnprice** [comment]
#979 was fixed in yesterday's release 30.0.261 ([#announce > mobile releases @ 💬](https://chat.zulip.org/#narrow/channel/1-announce/topic/mobile.20releases/near/2217685)), which was the last of the issues mentioned in https://github.com/zulip/zulip-flutter/issues/1525#issuecomment-2920818667 above; the other four (#196, #81, #80, #82) were all fixed in previous releases over the past few weeks. Thanks again @bkraul for the feedback!

Are you still seeing the symptoms discussed in https://github.com/zulip/zulip-flutter/issues/1525#issuecomment-2920818504 ?

**Comment by bkraul** [comment]
@gnprice will make sure I have the latest release and report back! Thanks!

**Comment by bkraul** [comment]
@gnprice is this release for the flutter app? or for the mainline app? I am not seeing the update on my flutter one ...

**Comment by bkraul** [comment]
@gnprice so I loaded the mainline app, which is the one that got updated to 30.0.261 but it appears it is indeed the flutter one that has now been fully released and replaced the old zulip-mobile one, ~~and the biggest issue with it is that push notifications do not work at all, I even tried to make sure the server was up to date (10.4) with registered push notifications, and nothing, so without that the rest is pretty much moot~~. I made sure to uninstall all versions of zulip on both phones. 

UPDATE: Notifications "do" work. It seems the logic to determine if you are on the desktop app or not has been fine-tuned or it is working as originally expected, I turned on "send mobile notifications even if online" and it did send them. I also tested on another device and they work as expected. Sorry for the false alarm there.

So far (early stages of full testing) I can see the loading bar at the top does come up but it goes away after a bit as expected. Mobile app message delivery works as expected while on the same WLAN, will be testing today outside and see how that goes.

**Comment by bkraul** [comment]
@gnprice We have been testing for about a week on this. While the application is working a bit more solid, we are still experiencing situations where messages are not received by the mobile app. The loading animations still come up and sometimes do get stuck for a bit but at least they do eventually go away. Really my main concern is the messages not being received. I wish there was a way I could turn on logging or something that I could see "why" messages don't get delivered, but this makes the application hard to use for day-to-day.

**Comment by gnprice** [comment]
Thanks for the update. Does the pattern of what you're seeing match the following issue?
* #1717 

That's a bug which sounds like it could be a match, and which we diagnosed and fixed last Friday. The fix will go out in the next release, anticipated for this week.

**Comment by gnprice** [comment]
Thanks @bkraul for your reports in this thread. I believe we've resolved all the issues you were seeing, so I'm closing this issue thread.

If you're seeing these or any other symptoms today, we'd be glad to hear about them; please go ahead and file a fresh issue thread for any of those.
